[package]
name = "content"
description = "Map/NPC/route manifest loading, versioning, and validation."
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
common = { version = "0.1.0", path = "../common" }
serde = { version = "1.0.229", features = ["derive"] }
serde_yaml = "0.9.34"
